"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "de" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.yachts": "Our Yachts",
    "nav.itineraries": "Itineraries",
    "nav.destinations": "Destinations",
    "nav.about": "About Us",
    "nav.blog": "Blog",
    "nav.contact": "Contact",
    "nav.booking": "Book Now",

    // Home Hero
    "home.hero.badge": "Luxury Blue Cruise Since 1989",
    "home.hero.title": "Discover Turkey's Turquoise Coast in Ultimate Luxury",
    "home.hero.subtitle": "Experience an unforgettable blue cruise aboard our handcrafted gulets. Crystal-clear waters, ancient ruins, and five-star service await you.",
    "home.hero.cta.fleet": "Explore Our Fleet",
    "home.hero.cta.contact": "Get a Quote",

    // Home Features
    "home.features.experience.title": "35+ Years Experience",
    "home.features.experience.desc": "Trusted by thousands of guests since 1989",
    "home.features.crew.title": "Professional Crew",
    "home.features.crew.desc": "Experienced captain and attentive staff",
    "home.features.cuisine.title": "Gourmet Cuisine",
    "home.features.cuisine.desc": "Full board with Mediterranean delights",
    "home.features.certified.title": "TURSAB Certified",
    "home.features.certified.desc": "Licensed travel agency #1739",

    // Home Fleet
    "home.fleet.badge": "Our Fleet",
    "home.fleet.title": "Handcrafted Luxury Gulets",
    "home.fleet.subtitle": "Choose from our collection of beautifully maintained gulets, each offering unique character and world-class amenities.",
    "home.fleet.viewAll": "View All Yachts",

    // Home Itineraries
    "home.itineraries.badge": "Itineraries",
    "home.itineraries.title": "Explore Our Routes",
    "home.itineraries.subtitle": "Discover the best of the Turkish Riviera with our carefully curated sailing routes.",
    "home.itineraries.viewAll": "View All Itineraries",

    // Home About
    "home.about.title": "Your Gateway to the Mediterranean Dream",
    "home.about.desc1": "Since 1989, Holiday Yacht has been crafting unforgettable blue cruise experiences along Turkey's stunning Turquoise Coast. As part of the Light Tours family, we combine decades of maritime expertise with genuine Turkish hospitality.",
    "home.about.desc2": "Our fleet of handcrafted gulets represents the finest in traditional Turkish boat building, enhanced with modern comforts and amenities.",

    // Home Stats
    "home.stats.years": "Years of Excellence",
    "home.stats.yachts": "Luxury Gulets",
    "home.stats.guests": "Happy Guests",
    "home.stats.support": "Support",
    "home.stats.satisfaction": "Satisfaction",
    "home.stats.destinations": "Destinations",

    // Home Testimonials
    "home.testimonials.badge": "Testimonials",
    "home.testimonials.title": "What Our Guests Say",
    "home.testimonial1": "An absolutely magical experience! The crew was exceptional, the food was incredible, and the scenery was breathtaking. We'll definitely be back!",
    "home.testimonial2": "From booking to disembarkation, everything was perfect. The yacht was beautiful and immaculately maintained. Best holiday we've ever had!",
    "home.testimonial3": "The attention to detail is remarkable. Swimming in crystal-clear bays and dining under the stars - it doesn't get better than this.",

    // Home CTA
    "home.cta.title": "Ready for Your Dream Voyage?",
    "home.cta.subtitle": "Let us help you plan the perfect blue cruise experience. Contact us today for a personalized quote.",
    "home.cta.button": "Plan Your Voyage",

    // Home Partners
    "home.partners.partOf": "Part of",

    // Yachts Page
    "yachts.badge": "Premium Gulet Collection",
    "yachts.title": "Our Fleet",
    "yachts.subtitle": "Discover our handpicked selection of luxury gulets, each offering exceptional comfort and authentic Turkish craftsmanship.",
    "yachts.stats.gulets": "Luxury Gulets",
    "yachts.stats.capacity": "Guest Capacity",
    "yachts.stats.length": "Length Range",
    "yachts.stats.builtYears": "Built Years",
    "yachts.featured": "Featured Yacht",
    "yachts.allYachts": "All Yachts",
    "yachts.whyChoose": "Why Choose Our Fleet?",
    "yachts.whyChooseDesc": "Every yacht in our fleet meets the highest standards of safety, comfort, and luxury.",
    "yachts.why.quality.title": "Premium Quality",
    "yachts.why.quality.desc": "Each gulet is handcrafted by master shipbuilders using traditional techniques and the finest materials.",
    "yachts.why.crew.title": "Expert Crew",
    "yachts.why.crew.desc": "Our professional crew members are trained to provide exceptional service while ensuring your safety.",
    "yachts.why.amenities.title": "Modern Amenities",
    "yachts.why.amenities.desc": "Enjoy contemporary comforts including air conditioning, WiFi, and entertainment systems.",

    // Yacht Filters
    "yachts.filters.title": "Filter Yachts",
    "yachts.filters.guests": "Guests",
    "yachts.filters.length": "Length",
    "yachts.filters.weeklyPrice": "Weekly Price",
    "yachts.filters.anyGuests": "Any capacity",
    "yachts.filters.anyLength": "Any length",
    "yachts.filters.anyPrice": "Any price",
    "yachts.filters.under15k": "Under €15,000",
    "yachts.filters.under20k": "Under €20,000",
    "yachts.filters.under25k": "Under €25,000",
    "yachts.filters.clear": "Clear filters",
    "yachts.filters.active": "Active",
    "yachts.filters.noResults": "No yachts match your filters",
    "yachts.filters.noResultsDesc": "Try adjusting your filter criteria",

    // Yacht Details
    "yacht.cabins": "Cabins",
    "yacht.guests": "Guests",
    "yacht.length": "Length",
    "yacht.crew": "Crew",
    "yacht.priceFrom": "From",
    "yacht.perWeek": "/week",
    "yacht.bookNow": "Book This Yacht",
    "yacht.requestQuote": "Request Quote",
    "yacht.amenities": "Amenities",
    "yacht.specifications": "Specifications",
    "yacht.gallery": "Gallery",
    "yacht.overview": "Overview",
    "yacht.features": "Features",
    "yacht.seasonPrices": "Seasonal Prices",
    "yacht.lowSeason": "Low Season",
    "yacht.midSeason": "Mid Season",
    "yacht.highSeason": "High Season",
    "yacht.aprilMay": "April - May",
    "yacht.juneSeptember": "June & September",
    "yacht.julyAugust": "July - August",
    "yacht.october": "October",
    "yacht.perDayShort": "/day",

    // Booking
    "booking.title": "Book Your Charter",
    "booking.subtitle": "Check availability and reserve your dream yacht in just a few steps.",
    "booking.selectYacht": "Select Your Yacht",
    "booking.selectYachtDesc": "Choose from our fleet of luxury gulets.",
    "booking.selectDates": "Select Your Dates",
    "booking.minNights": "Min. 7 nights",
    "booking.available": "Available",
    "booking.booked": "Booked",
    "booking.selected": "Selected",
    "booking.checkIn": "Check-in",
    "booking.checkOut": "Check-out",
    "booking.duration": "Duration",
    "booking.nights": "nights",
    "booking.guestDetails": "Guest Details",
    "booking.firstName": "First Name",
    "booking.lastName": "Last Name",
    "booking.email": "Email Address",
    "booking.phone": "Phone Number",
    "booking.country": "Country",
    "booking.guests": "Number of Guests",
    "booking.specialRequests": "Special Requests",
    "booking.submit": "Request Booking",
    "booking.changeYacht": "← Change Yacht",
    "booking.whyBookDirect": "Why Book Directly With Us?",
    "booking.bestPrice": "Best Price Guarantee",
    "booking.noHiddenFees": "No Hidden Fees",
    "booking.flexibleCancellation": "Flexible Cancellation",
    "booking.support247": "24/7 Support",
    "booking.needHelp": "Need help with your booking?",

    // Booking Form
    "bookingForm.confirmation": "Confirmation",
    "bookingForm.priceSummary": "Price Summary",
    "bookingForm.fullBoardIncluded": "Full board included",
    "bookingForm.total": "Total",
    "bookingForm.continueToDetails": "Continue to Details",
    "bookingForm.guestInfo": "Guest Information",
    "bookingForm.firstNameRequired": "First name is required",
    "bookingForm.lastNameRequired": "Last name is required",
    "bookingForm.emailRequired": "Email is required",
    "bookingForm.emailInvalid": "Invalid email address",
    "bookingForm.phoneRequired": "Phone is required",
    "bookingForm.countryRequired": "Country is required",
    "bookingForm.guest": "guest",
    "bookingForm.specialRequestsPlaceholder": "Any dietary requirements, special occasions, or preferences...",
    "bookingForm.agreeToTerms": "I agree to the",
    "bookingForm.termsConditions": "Terms & Conditions",
    "bookingForm.and": "and",
    "bookingForm.privacyPolicy": "Privacy Policy",
    "bookingForm.termsRequired": "You must agree to the terms",
    "bookingForm.back": "Back",
    "bookingForm.requestSubmitted": "Booking Request Submitted!",
    "bookingForm.thankYou": "Thank you for your interest in",
    "bookingForm.willContact": "Our team will review your request and contact you within 24 hours to confirm your booking.",
    "bookingForm.bookingSummary": "Booking Summary",
    "bookingForm.yacht": "Yacht",
    "bookingForm.dates": "Dates",
    "bookingForm.returnHome": "Return to Homepage",

    // Calendar
    "calendar.selectDates": "Select Your Dates",
    "calendar.minNights": "Min. {min} nights",
    "calendar.available": "Available",
    "calendar.booked": "Booked",
    "calendar.selected": "Selected",
    "calendar.checkIn": "Check-in",
    "calendar.checkOut": "Check-out",
    "calendar.duration": "Duration",
    "calendar.nights": "nights",
    "calendar.minNightsWarning": "Please select at least {min} nights",

    // Yacht Detail Page
    "yachtDetail.backToFleet": "Back to Fleet",
    "yachtDetail.about": "About",
    "yachtDetail.photoGallery": "Photo Gallery",
    "yachtDetail.amenitiesFeatures": "Amenities & Features",
    "yachtDetail.startingFrom": "Starting from",
    "yachtDetail.perWeek": "per week",
    "yachtDetail.perDay": "per day",
    "yachtDetail.minDays": "Minimum {days} days charter",
    "yachtDetail.notIncluded": "Not included:",
    "yachtDetail.callForQuote": "Call for Quote",
    "yachtDetail.sendInquiry": "Send Inquiry",
    "yachtDetail.charterIncludes": "Charter includes:",
    "yachtDetail.professionalCrew": "Professional crew",
    "yachtDetail.fullBoardMeals": "Full board meals",
    "yachtDetail.fuelCruising": "Fuel for cruising",
    "yachtDetail.waterSports": "Water sports equipment",
    "yachtDetail.portFees": "Port fees",
    "yachtDetail.built": "Built",
    "yachtDetail.renovated": "Renovated",

    // Itinerary Detail Page
    "itineraryDetail.allItineraries": "All Itineraries",
    "itineraryDetail.days": "Days",
    "itineraryDetail.dayByDay": "Day by Day Itinerary",
    "itineraryDetail.dayByDayDesc": "Your journey unfolds with carefully planned stops, activities, and experiences designed to showcase the best of the region.",
    "itineraryDetail.recommendedYachts": "Recommended Yachts",
    "itineraryDetail.recommendedYachtsDesc": "These yachts are perfectly suited for this itinerary, offering the ideal combination of comfort and capability.",
    "itineraryDetail.readyToExperience": "Ready to Experience This Route?",
    "itineraryDetail.contactUs": "Contact us to check availability and receive a personalized quote for your dream sailing adventure.",
    "itineraryDetail.getQuote": "Get a Quote",

    // Contact
    "contact.title": "Contact Us",
    "contact.subtitle": "Have questions or ready to book your dream voyage?",
    "contact.phone": "Phone",
    "contact.email": "Email",
    "contact.address": "Address",
    "contact.workingHours": "Working Hours",
    "contact.sendMessage": "Send Us a Message",
    "contact.sendMessageDesc": "Fill out the form and we'll get back to you within 24 hours.",
    "contact.yourName": "Your Name",
    "contact.yourEmail": "Email Address",
    "contact.phoneNumber": "Phone Number",
    "contact.subject": "Subject",
    "contact.selectSubject": "Select a subject",
    "contact.subjectBooking": "Booking Inquiry",
    "contact.subjectQuote": "Request a Quote",
    "contact.subjectInfo": "General Information",
    "contact.subjectCustom": "Custom Itinerary",
    "contact.subjectOther": "Other",
    "contact.interestedYacht": "Interested in a Yacht?",
    "contact.selectYacht": "Select a yacht (optional)",
    "contact.yourMessage": "Your Message",
    "contact.messagePlaceholder": "Tell us about your dream voyage...",
    "contact.send": "Send Message",
    "contact.messageSent": "Message Sent!",
    "contact.messageSentDesc": "Thank you for contacting us.",
    "contact.sendAnother": "Send Another Message",
    "contact.immediateHelp": "Need Immediate Help?",
    "contact.immediateHelpDesc": "Our team is available during business hours.",

    // About
    "about.badge": "Since 1989",
    "about.title": "About Holiday Yacht",
    "about.subtitle": "Over three decades of crafting unforgettable blue cruise experiences.",
    "about.stats.years": "Years Experience",
    "about.stats.gulets": "Luxury Gulets",
    "about.stats.guests": "Happy Guests",
    "about.stats.destinations": "Destinations",
    "about.story.badge": "Our Story",
    "about.story.title": "A Legacy of Excellence on the Turquoise Coast",
    "about.story.p1": "Founded in 1989 in the charming coastal town of Fethiye, Holiday Yacht began with a simple vision: to share the breathtaking beauty of Turkey's Mediterranean coastline with travelers from around the world.",
    "about.story.p2": "As part of the Light Tours family, we have grown from a small local operation into one of the region's most respected yacht charter companies.",
    "about.story.p3": "Today, we continue to uphold the values that have guided us for over 35 years: exceptional service, authentic experiences, and an unwavering commitment to guest satisfaction.",
    "about.values.badge": "Our Values",
    "about.values.title": "What Sets Us Apart",
    "about.values.safety": "Safety First",
    "about.values.safetyDesc": "Your safety is our top priority.",
    "about.values.hospitality": "Genuine Hospitality",
    "about.values.hospitalityDesc": "Experience authentic Turkish hospitality.",
    "about.values.excellence": "Excellence",
    "about.values.excellenceDesc": "We strive for excellence in every aspect.",
    "about.values.personal": "Personal Touch",
    "about.values.personalDesc": "Every charter is tailored to your preferences.",
    "about.team.badge": "Our Team",
    "about.team.title": "Meet the Crew",
    "about.team.subtitle": "Our experienced crew members are the heart of Holiday Yacht.",
    "about.team.captain": "Captain",
    "about.team.captainDesc": "Expert navigators with decades of experience.",
    "about.team.chef": "Chef",
    "about.team.chefDesc": "Culinary artists creating delicious Mediterranean cuisine.",
    "about.team.crew": "Crew",
    "about.team.crewDesc": "Attentive staff ensuring your comfort and safety.",
    "about.cta.title": "Ready to Start Your Journey?",
    "about.cta.subtitle": "Let us help you create memories that will last a lifetime.",
    "about.cta.fleet": "Explore Our Fleet",
    "about.cta.contact": "Contact Us",
    "about.lightTours.title": "Part of the Light Tours Family",
    "about.lightTours.desc": "Holiday Yacht is proud to be part of Light Tours, a comprehensive travel agency.",

    // Itineraries
    "itineraries.badge": "Curated Routes",
    "itineraries.title": "Sailing Itineraries",
    "itineraries.subtitle": "Discover the magic of the Turkish Riviera with our expertly planned routes.",
    "itineraries.days": "Days",
    "itineraries.highlights": "Highlights",
    "itineraries.viewFull": "View Full Itinerary",
    "itineraries.dayByDay": "Day by Day Itinerary",
    "itineraries.dayByDayDesc": "Your journey unfolds with carefully planned stops and experiences.",
    "itineraries.recommendedYachts": "Recommended Yachts",
    "itineraries.recommendedYachtsDesc": "These yachts are perfectly suited for this itinerary.",
    "itineraries.customRoute": "Looking for a Custom Route?",
    "itineraries.customRouteDesc": "We can create a personalized itinerary based on your preferences.",
    "itineraries.requestCustom": "Request Custom Itinerary",
    "itineraries.readyToExperience": "Ready to Experience This Route?",
    "itineraries.checkAvailability": "Check Availability",
    "itineraries.getQuote": "Get a Quote",
    "itineraries.allRoutes": "All Itineraries",

    // Error Pages
    "error.pageNotFound": "Page Not Found",
    "error.pageNotFoundDesc": "The page you're looking for seems to have sailed away. Perhaps it's exploring the Turkish coast!",
    "error.backToHome": "Back to Home",
    "error.viewFleet": "View Our Fleet",
    "error.contactUs": "Contact Us",

    // Footer
    "footer.description": "Premium gulet charters along Turkey's stunning Turquoise Coast since 1989.",
    "footer.quickLinks": "Quick Links",
    "footer.contactInfo": "Contact Info",
    "footer.followUs": "Follow Us",
    "footer.rights": "All rights reserved.",
    "footer.tursab": "TURSAB License #1739",
    "footer.workingHours": "Mon - Sat: 09:00 - 18:00",

    // Common
    "common.select": "Select",
    "common.viewDetails": "View Details",
    "common.learnMore": "Learn More",
    "common.callUs": "Call Us",

    // Search
    "search.placeholder": "Search yachts, destinations, itineraries...",
    "search.noResults": "No results found",
    "search.quickLinks": "Quick Links",
    "search.hint": "Type to search",
    "search.toClose": "to close",

    // Favorites
    "favorites.title": "My Favorites",
    "favorites.subtitle": "Your saved yachts and itineraries",
    "favorites.empty": "No favorites yet",
    "favorites.emptyDesc": "Save yachts and itineraries you love by clicking the heart icon",
    "favorites.browseYachts": "Browse Yachts",
    "favorites.browseItineraries": "Browse Itineraries",
    "favorites.yachts": "Yachts",
    "favorites.itineraries": "Itineraries",
    "favorites.destinations": "Destinations",
    "favorites.clearAll": "Clear All",
    "favorites.addedToFavorites": "Added to favorites",
    "favorites.removedFromFavorites": "Removed from favorites",

    "common.whatsapp": "WhatsApp",
    "common.loading": "Loading...",
    "common.from": "From",
    "common.perWeek": "per week",
    "common.share": "Share",

    // Blog
    "blog.badge": "Our Blog",
    "blog.title": "Blue Cruise Insights & Travel Tips",
    "blog.subtitle": "Expert advice, destination guides, and insider tips for your perfect yacht charter experience",
    "blog.allPosts": "All Posts",
    "blog.destinations": "Destinations",
    "blog.tips": "Tips & Advice",
    "blog.guides": "Guides",
    "blog.news": "News",
    "blog.readMore": "Read More",
    "blog.minRead": "min read",
    "blog.backToBlog": "Back to Blog",
    "blog.relatedArticles": "Related Articles",
    "blog.moreFromBlog": "More from Our Blog",
    "blog.popularTopics": "Popular Topics",
    "blog.readyForCruise": "Ready for Your Blue Cruise?",
    "blog.contactUsDesc": "Contact us to plan your perfect yacht charter experience along the Turkish coast.",
    "blog.getQuote": "Get a Quote",
    "blog.stayUpdated": "Stay Updated with Our Latest Articles",
    "blog.subscribeDesc": "Subscribe to our newsletter for exclusive travel tips, special offers, and insider guides to the Turkish coast.",
    "blog.subscribeNow": "Subscribe Now",
    "blog.shareArticle": "Share this article:",
    "blog.noPosts": "No posts found in this category.",

    // Destinations
    "destinations.badge": "Explore Turkey",
    "destinations.title": "Sailing Destinations",
    "destinations.subtitle": "Discover the stunning harbors and coastal gems of Turkey's Turquoise Coast, each offering unique experiences for your Blue Cruise adventure",
    "destinations.turquoiseAwaits": "The Turquoise Coast Awaits",
    "destinations.turquoiseDesc": "Turkey's southwestern coast is home to some of the Mediterranean's most spectacular sailing waters. From ancient harbor towns to pristine bays, each destination offers its own character and attractions.",
    "destinations.explore": "Explore",
    "destinations.notSure": "Not Sure Where to Start?",
    "destinations.notSureDesc": "Our team knows every bay and harbor along the Turkish coast. Let us help you choose the perfect itinerary for your dream Blue Cruise.",
    "destinations.contactExperts": "Contact Our Experts",
    "destinations.about": "About",
    "destinations.whyVisit": "Why Visit",
    "destinations.mustSee": "Must-See Attractions",
    "destinations.itinerariesFrom": "Itineraries from",
    "destinations.planCruise": "Plan Your",
    "destinations.planCruiseDesc": "Contact us to start planning your perfect Blue Cruise from",
    "destinations.idealFor": "Ideal For",
    "destinations.bestTime": "Best Time to Visit",
    "destinations.sailInStyle": "Sail",
    "destinations.sailInStyleDesc": "Explore our fleet of luxury gulets, all available for charters from",
    "destinations.exploreOther": "Explore Other Destinations",
    "destinations.viewAll": "View All Destinations",
    "destinations.allDestinations": "All Destinations",
    "destinations.turkey": "Turkey",

    // Newsletter
    "newsletter.title": "Subscribe to Our Newsletter",
    "newsletter.subtitle": "Get exclusive travel tips, special offers, and insider guides to the Turkish coast delivered to your inbox.",
    "newsletter.placeholder": "Enter your email address",
    "newsletter.subscribe": "Subscribe Now",
    "newsletter.subscribing": "Subscribing...",
    "newsletter.success": "Thank you for subscribing! Check your inbox for a confirmation email.",
    "newsletter.error": "Something went wrong. Please try again later.",
    "newsletter.invalidEmail": "Please enter a valid email address",
    "newsletter.required": "Please enter your email address",
    "newsletter.privacy": "No spam, unsubscribe anytime. We respect your privacy.",
    "newsletter.compact.title": "Newsletter",
    "newsletter.compact.subtitle": "Get travel tips & exclusive offers",
    "newsletter.compact.subscribed": "Subscribed!",
  },
  de: {
    // Navigation
    "nav.home": "Startseite",
    "nav.yachts": "Unsere Yachten",
    "nav.itineraries": "Routen",
    "nav.destinations": "Reiseziele",
    "nav.about": "Über Uns",
    "nav.blog": "Blog",
    "nav.contact": "Kontakt",
    "nav.booking": "Jetzt Buchen",

    // Home Hero
    "home.hero.badge": "Luxus Blaue Reise Seit 1989",
    "home.hero.title": "Entdecken Sie die Türkische Türkisküste in Ultimativem Luxus",
    "home.hero.subtitle": "Erleben Sie eine unvergessliche Blaue Reise an Bord unserer handgefertigten Gulets. Kristallklares Wasser, antike Ruinen und Fünf-Sterne-Service erwarten Sie.",
    "home.hero.cta.fleet": "Unsere Flotte Entdecken",
    "home.hero.cta.contact": "Angebot Anfordern",

    // Home Features
    "home.features.experience.title": "35+ Jahre Erfahrung",
    "home.features.experience.desc": "Vertrauen von Tausenden Gästen seit 1989",
    "home.features.crew.title": "Professionelle Crew",
    "home.features.crew.desc": "Erfahrener Kapitän und aufmerksames Personal",
    "home.features.cuisine.title": "Gourmet-Küche",
    "home.features.cuisine.desc": "Vollpension mit mediterranen Köstlichkeiten",
    "home.features.certified.title": "TÜRSAB Zertifiziert",
    "home.features.certified.desc": "Lizenzierte Reiseagentur #1739",

    // Home Fleet
    "home.fleet.badge": "Unsere Flotte",
    "home.fleet.title": "Handgefertigte Luxus-Gulets",
    "home.fleet.subtitle": "Wählen Sie aus unserer Sammlung sorgfältig gepflegter Gulets mit einzigartigem Charakter und erstklassiger Ausstattung.",
    "home.fleet.viewAll": "Alle Yachten Ansehen",

    // Home Itineraries
    "home.itineraries.badge": "Routen",
    "home.itineraries.title": "Entdecken Sie Unsere Routen",
    "home.itineraries.subtitle": "Entdecken Sie das Beste der türkischen Riviera mit unseren sorgfältig geplanten Segelrouten.",
    "home.itineraries.viewAll": "Alle Routen Ansehen",

    // Home About
    "home.about.title": "Ihr Tor zum Mittelmeertraum",
    "home.about.desc1": "Seit 1989 kreiert Holiday Yacht unvergessliche Blaue-Reise-Erlebnisse entlang der atemberaubenden Türkisküste der Türkei. Als Teil der Light Tours Familie verbinden wir jahrzehntelange maritime Expertise mit echter türkischer Gastfreundschaft.",
    "home.about.desc2": "Unsere Flotte handgefertigter Gulets repräsentiert das Beste des traditionellen türkischen Bootsbaus, erweitert um modernen Komfort und Annehmlichkeiten.",

    // Home Stats
    "home.stats.years": "Jahre Exzellenz",
    "home.stats.yachts": "Luxus-Gulets",
    "home.stats.guests": "Zufriedene Gäste",
    "home.stats.support": "Support",
    "home.stats.satisfaction": "Zufriedenheit",
    "home.stats.destinations": "Reiseziele",

    // Home Testimonials
    "home.testimonials.badge": "Gästebewertungen",
    "home.testimonials.title": "Was Unsere Gäste Sagen",
    "home.testimonial1": "Ein absolut magisches Erlebnis! Die Crew war außergewöhnlich, das Essen war unglaublich und die Landschaft war atemberaubend. Wir kommen definitiv wieder!",
    "home.testimonial2": "Von der Buchung bis zum Verlassen war alles perfekt. Die Yacht war wunderschön und tadellos gepflegt. Der beste Urlaub, den wir je hatten!",
    "home.testimonial3": "Die Liebe zum Detail ist bemerkenswert. Schwimmen in kristallklaren Buchten und Essen unter den Sternen - besser geht es nicht.",

    // Home CTA
    "home.cta.title": "Bereit für Ihre Traumreise?",
    "home.cta.subtitle": "Lassen Sie uns Ihnen helfen, das perfekte Blaue-Reise-Erlebnis zu planen. Kontaktieren Sie uns noch heute für ein persönliches Angebot.",
    "home.cta.button": "Planen Sie Ihre Reise",

    // Home Partners
    "home.partners.partOf": "Teil von",

    // Yachts Page
    "yachts.badge": "Premium Gulet-Kollektion",
    "yachts.title": "Unsere Flotte",
    "yachts.subtitle": "Entdecken Sie unsere handverlesene Auswahl an Luxus-Gulets, die außergewöhnlichen Komfort und authentisches türkisches Handwerk bieten.",
    "yachts.stats.gulets": "Luxus-Gulets",
    "yachts.stats.capacity": "Gästekapazität",
    "yachts.stats.length": "Längenbereich",
    "yachts.stats.builtYears": "Baujahre",
    "yachts.featured": "Vorgestellte Yacht",
    "yachts.allYachts": "Alle Yachten",
    "yachts.whyChoose": "Warum Unsere Flotte Wählen?",
    "yachts.whyChooseDesc": "Jede Yacht in unserer Flotte erfüllt die höchsten Standards für Sicherheit, Komfort und Luxus.",
    "yachts.why.quality.title": "Premium-Qualität",
    "yachts.why.quality.desc": "Jede Gulet wird von Meisterschiffbauern unter Verwendung traditioneller Techniken und feinster Materialien handgefertigt.",
    "yachts.why.crew.title": "Experten-Crew",
    "yachts.why.crew.desc": "Unsere professionellen Besatzungsmitglieder sind geschult, außergewöhnlichen Service zu bieten und Ihre Sicherheit zu gewährleisten.",
    "yachts.why.amenities.title": "Moderne Ausstattung",
    "yachts.why.amenities.desc": "Genießen Sie zeitgenössischen Komfort mit Klimaanlage, WLAN und Unterhaltungssystemen.",

    // Yacht Filters
    "yachts.filters.title": "Yachten filtern",
    "yachts.filters.guests": "Gäste",
    "yachts.filters.length": "Länge",
    "yachts.filters.weeklyPrice": "Wochenpreis",
    "yachts.filters.anyGuests": "Beliebige Kapazität",
    "yachts.filters.anyLength": "Beliebige Länge",
    "yachts.filters.anyPrice": "Beliebiger Preis",
    "yachts.filters.under15k": "Unter €15.000",
    "yachts.filters.under20k": "Unter €20.000",
    "yachts.filters.under25k": "Unter €25.000",
    "yachts.filters.clear": "Filter löschen",
    "yachts.filters.active": "Aktiv",
    "yachts.filters.noResults": "Keine Yachten entsprechen Ihren Filtern",
    "yachts.filters.noResultsDesc": "Versuchen Sie, Ihre Filterkriterien anzupassen",

    // Yacht Details
    "yacht.cabins": "Kabinen",
    "yacht.guests": "Gäste",
    "yacht.length": "Länge",
    "yacht.crew": "Besatzung",
    "yacht.priceFrom": "Ab",
    "yacht.perWeek": "/Woche",
    "yacht.bookNow": "Diese Yacht Buchen",
    "yacht.requestQuote": "Angebot Anfordern",
    "yacht.amenities": "Ausstattung",
    "yacht.specifications": "Spezifikationen",
    "yacht.gallery": "Galerie",
    "yacht.overview": "Überblick",
    "yacht.features": "Merkmale",
    "yacht.seasonPrices": "Saisonpreise",
    "yacht.lowSeason": "Nebensaison",
    "yacht.midSeason": "Zwischensaison",
    "yacht.highSeason": "Hauptsaison",
    "yacht.aprilMay": "April - Mai",
    "yacht.juneSeptember": "Juni & September",
    "yacht.julyAugust": "Juli - August",
    "yacht.october": "Oktober",
    "yacht.perDayShort": "/Tag",

    // Booking
    "booking.title": "Charter Buchen",
    "booking.subtitle": "Prüfen Sie die Verfügbarkeit und reservieren Sie Ihre Traumyacht in wenigen Schritten.",
    "booking.selectYacht": "Wählen Sie Ihre Yacht",
    "booking.selectYachtDesc": "Wählen Sie aus unserer Luxus-Gulet-Flotte.",
    "booking.selectDates": "Wählen Sie Ihre Daten",
    "booking.minNights": "Min. 7 Nächte",
    "booking.available": "Verfügbar",
    "booking.booked": "Gebucht",
    "booking.selected": "Ausgewählt",
    "booking.checkIn": "Check-in",
    "booking.checkOut": "Check-out",
    "booking.duration": "Dauer",
    "booking.nights": "Nächte",
    "booking.guestDetails": "Gastdetails",
    "booking.firstName": "Vorname",
    "booking.lastName": "Nachname",
    "booking.email": "E-Mail-Adresse",
    "booking.phone": "Telefonnummer",
    "booking.country": "Land",
    "booking.guests": "Anzahl der Gäste",
    "booking.specialRequests": "Besondere Wünsche",
    "booking.submit": "Buchung Anfragen",
    "booking.changeYacht": "← Yacht Ändern",
    "booking.whyBookDirect": "Warum Direkt Bei Uns Buchen?",
    "booking.bestPrice": "Bestpreisgarantie",
    "booking.noHiddenFees": "Keine Versteckten Gebühren",
    "booking.flexibleCancellation": "Flexible Stornierung",
    "booking.support247": "24/7 Support",
    "booking.needHelp": "Brauchen Sie Hilfe bei Ihrer Buchung?",

    // Booking Form
    "bookingForm.confirmation": "Bestätigung",
    "bookingForm.priceSummary": "Preisübersicht",
    "bookingForm.fullBoardIncluded": "Vollpension inklusive",
    "bookingForm.total": "Gesamt",
    "bookingForm.continueToDetails": "Weiter zu den Details",
    "bookingForm.guestInfo": "Gäste-Informationen",
    "bookingForm.firstNameRequired": "Vorname ist erforderlich",
    "bookingForm.lastNameRequired": "Nachname ist erforderlich",
    "bookingForm.emailRequired": "E-Mail ist erforderlich",
    "bookingForm.emailInvalid": "Ungültige E-Mail-Adresse",
    "bookingForm.phoneRequired": "Telefon ist erforderlich",
    "bookingForm.countryRequired": "Land ist erforderlich",
    "bookingForm.guest": "Gast",
    "bookingForm.specialRequestsPlaceholder": "Diätanforderungen, besondere Anlässe oder Präferenzen...",
    "bookingForm.agreeToTerms": "Ich stimme den",
    "bookingForm.termsConditions": "AGB",
    "bookingForm.and": "und der",
    "bookingForm.privacyPolicy": "Datenschutzerklärung",
    "bookingForm.termsRequired": "Sie müssen den Bedingungen zustimmen",
    "bookingForm.back": "Zurück",
    "bookingForm.requestSubmitted": "Buchungsanfrage Gesendet!",
    "bookingForm.thankYou": "Vielen Dank für Ihr Interesse an",
    "bookingForm.willContact": "Unser Team wird Ihre Anfrage prüfen und Sie innerhalb von 24 Stunden kontaktieren, um Ihre Buchung zu bestätigen.",
    "bookingForm.bookingSummary": "Buchungsübersicht",
    "bookingForm.yacht": "Yacht",
    "bookingForm.dates": "Daten",
    "bookingForm.returnHome": "Zur Startseite",

    // Calendar
    "calendar.selectDates": "Wählen Sie Ihre Termine",
    "calendar.minNights": "Min. {min} Nächte",
    "calendar.available": "Verfügbar",
    "calendar.booked": "Gebucht",
    "calendar.selected": "Ausgewählt",
    "calendar.checkIn": "Check-in",
    "calendar.checkOut": "Check-out",
    "calendar.duration": "Dauer",
    "calendar.nights": "Nächte",
    "calendar.minNightsWarning": "Bitte wählen Sie mindestens {min} Nächte",

    // Yacht Detail Page
    "yachtDetail.backToFleet": "Zurück zur Flotte",
    "yachtDetail.about": "Über",
    "yachtDetail.photoGallery": "Fotogalerie",
    "yachtDetail.amenitiesFeatures": "Ausstattung & Merkmale",
    "yachtDetail.startingFrom": "Ab",
    "yachtDetail.perWeek": "pro Woche",
    "yachtDetail.perDay": "pro Tag",
    "yachtDetail.minDays": "Mindestens {days} Tage Charter",
    "yachtDetail.notIncluded": "Nicht inbegriffen:",
    "yachtDetail.callForQuote": "Anruf für Angebot",
    "yachtDetail.sendInquiry": "Anfrage Senden",
    "yachtDetail.charterIncludes": "Charter beinhaltet:",
    "yachtDetail.professionalCrew": "Professionelle Besatzung",
    "yachtDetail.fullBoardMeals": "Vollpension",
    "yachtDetail.fuelCruising": "Treibstoff für Fahrten",
    "yachtDetail.waterSports": "Wassersportausrüstung",
    "yachtDetail.portFees": "Hafengebühren",
    "yachtDetail.built": "Baujahr",
    "yachtDetail.renovated": "Renoviert",

    // Itinerary Detail Page
    "itineraryDetail.allItineraries": "Alle Routen",
    "itineraryDetail.days": "Tage",
    "itineraryDetail.dayByDay": "Tag für Tag Reiseplan",
    "itineraryDetail.dayByDayDesc": "Ihre Reise entfaltet sich mit sorgfältig geplanten Stopps, Aktivitäten und Erlebnissen, die das Beste der Region zeigen.",
    "itineraryDetail.recommendedYachts": "Empfohlene Yachten",
    "itineraryDetail.recommendedYachtsDesc": "Diese Yachten sind perfekt für diese Route geeignet und bieten die ideale Kombination aus Komfort und Leistung.",
    "itineraryDetail.readyToExperience": "Bereit, Diese Route zu Erleben?",
    "itineraryDetail.contactUs": "Kontaktieren Sie uns, um die Verfügbarkeit zu prüfen und ein personalisiertes Angebot für Ihr Traum-Segelabenteuer zu erhalten.",
    "itineraryDetail.getQuote": "Angebot Anfordern",

    // Contact
    "contact.title": "Kontakt",
    "contact.subtitle": "Haben Sie Fragen oder sind Sie bereit, Ihre Traumreise zu buchen?",
    "contact.phone": "Telefon",
    "contact.email": "E-Mail",
    "contact.address": "Adresse",
    "contact.workingHours": "Öffnungszeiten",
    "contact.sendMessage": "Senden Sie Uns Eine Nachricht",
    "contact.sendMessageDesc": "Füllen Sie das Formular aus und wir melden uns innerhalb von 24 Stunden.",
    "contact.yourName": "Ihr Name",
    "contact.yourEmail": "E-Mail-Adresse",
    "contact.phoneNumber": "Telefonnummer",
    "contact.subject": "Betreff",
    "contact.selectSubject": "Betreff auswählen",
    "contact.subjectBooking": "Buchungsanfrage",
    "contact.subjectQuote": "Angebot Anfordern",
    "contact.subjectInfo": "Allgemeine Informationen",
    "contact.subjectCustom": "Individuelle Route",
    "contact.subjectOther": "Sonstiges",
    "contact.interestedYacht": "Interessiert an einer Yacht?",
    "contact.selectYacht": "Yacht auswählen (optional)",
    "contact.yourMessage": "Ihre Nachricht",
    "contact.messagePlaceholder": "Erzählen Sie uns von Ihrer Traumreise...",
    "contact.send": "Nachricht Senden",
    "contact.messageSent": "Nachricht Gesendet!",
    "contact.messageSentDesc": "Vielen Dank für Ihre Kontaktaufnahme.",
    "contact.sendAnother": "Weitere Nachricht Senden",
    "contact.immediateHelp": "Brauchen Sie Sofortige Hilfe?",
    "contact.immediateHelpDesc": "Unser Team ist während der Geschäftszeiten erreichbar.",

    // About
    "about.badge": "Seit 1989",
    "about.title": "Über Holiday Yacht",
    "about.subtitle": "Seit über drei Jahrzehnten unvergessliche Blaue-Reise-Erlebnisse.",
    "about.stats.years": "Jahre Erfahrung",
    "about.stats.gulets": "Luxus-Gulets",
    "about.stats.guests": "Zufriedene Gäste",
    "about.stats.destinations": "Reiseziele",
    "about.story.badge": "Unsere Geschichte",
    "about.story.title": "Ein Vermächtnis der Exzellenz an der Türkisküste",
    "about.story.p1": "Gegründet 1989 in der charmanten Küstenstadt Fethiye, begann Holiday Yacht mit einer einfachen Vision: die atemberaubende Schönheit der türkischen Mittelmeerküste mit Reisenden aus aller Welt zu teilen.",
    "about.story.p2": "Als Teil der Light Tours Familie sind wir von einem kleinen lokalen Unternehmen zu einer der angesehensten Yacht-Charter-Firmen der Region gewachsen.",
    "about.story.p3": "Heute halten wir die Werte aufrecht, die uns seit über 35 Jahren leiten: außergewöhnlicher Service, authentische Erlebnisse und unerschütterliches Engagement für Gästezufriedenheit.",
    "about.values.badge": "Unsere Werte",
    "about.values.title": "Was Uns Auszeichnet",
    "about.values.safety": "Sicherheit Zuerst",
    "about.values.safetyDesc": "Ihre Sicherheit hat höchste Priorität.",
    "about.values.hospitality": "Echte Gastfreundschaft",
    "about.values.hospitalityDesc": "Erleben Sie authentische türkische Gastfreundschaft.",
    "about.values.excellence": "Exzellenz",
    "about.values.excellenceDesc": "Wir streben in jedem Aspekt nach Exzellenz.",
    "about.values.personal": "Persönliche Note",
    "about.values.personalDesc": "Jeder Charter wird auf Ihre Wünsche zugeschnitten.",
    "about.team.badge": "Unser Team",
    "about.team.title": "Lernen Sie die Crew Kennen",
    "about.team.subtitle": "Unsere erfahrenen Besatzungsmitglieder sind das Herz von Holiday Yacht.",
    "about.team.captain": "Kapitän",
    "about.team.captainDesc": "Experten mit jahrzehntelanger Erfahrung.",
    "about.team.chef": "Koch",
    "about.team.chefDesc": "Kulinarische Künstler mit mediterraner Küche.",
    "about.team.crew": "Besatzung",
    "about.team.crewDesc": "Aufmerksames Personal für Ihren Komfort und Ihre Sicherheit.",
    "about.cta.title": "Bereit, Ihre Reise zu Beginnen?",
    "about.cta.subtitle": "Lassen Sie uns Ihnen helfen, Erinnerungen zu schaffen, die ein Leben lang halten.",
    "about.cta.fleet": "Unsere Flotte Entdecken",
    "about.cta.contact": "Kontaktieren Sie Uns",
    "about.lightTours.title": "Teil der Light Tours Familie",
    "about.lightTours.desc": "Holiday Yacht ist stolz darauf, Teil von Light Tours zu sein, einer umfassenden Reiseagentur.",

    // Itineraries
    "itineraries.badge": "Kuratierte Routen",
    "itineraries.title": "Segelrouten",
    "itineraries.subtitle": "Entdecken Sie die Magie der türkischen Riviera mit unseren fachmännisch geplanten Routen.",
    "itineraries.days": "Tage",
    "itineraries.highlights": "Highlights",
    "itineraries.viewFull": "Vollständige Route Ansehen",
    "itineraries.dayByDay": "Tag für Tag Reiseplan",
    "itineraries.dayByDayDesc": "Ihre Reise entfaltet sich mit sorgfältig geplanten Stopps und Erlebnissen.",
    "itineraries.recommendedYachts": "Empfohlene Yachten",
    "itineraries.recommendedYachtsDesc": "Diese Yachten sind perfekt für diese Route geeignet.",
    "itineraries.customRoute": "Suchen Sie eine Individuelle Route?",
    "itineraries.customRouteDesc": "Wir können eine personalisierte Route nach Ihren Wünschen erstellen.",
    "itineraries.requestCustom": "Individuelle Route Anfragen",
    "itineraries.readyToExperience": "Bereit, Diese Route zu Erleben?",
    "itineraries.checkAvailability": "Verfügbarkeit Prüfen",
    "itineraries.getQuote": "Angebot Anfordern",
    "itineraries.allRoutes": "Alle Routen",

    // Error Pages
    "error.pageNotFound": "Seite Nicht Gefunden",
    "error.pageNotFoundDesc": "Die gesuchte Seite scheint in See gestochen zu sein. Vielleicht erkundet sie gerade die türkische Küste!",
    "error.backToHome": "Zurück zur Startseite",
    "error.viewFleet": "Unsere Flotte Ansehen",
    "error.contactUs": "Kontaktieren Sie Uns",

    // Footer
    "footer.description": "Premium Gulet-Charter entlang der atemberaubenden Türkisküste seit 1989.",
    "footer.quickLinks": "Schnelllinks",
    "footer.contactInfo": "Kontaktinfo",
    "footer.followUs": "Folgen Sie Uns",
    "footer.rights": "Alle Rechte vorbehalten.",
    "footer.tursab": "TÜRSAB Lizenz #1739",
    "footer.workingHours": "Mo - Sa: 09:00 - 18:00",

    // Common
    "common.select": "Auswählen",
    "common.viewDetails": "Details Ansehen",
    "common.learnMore": "Mehr Erfahren",
    "common.callUs": "Rufen Sie Uns An",

    // Search
    "search.placeholder": "Yachten, Destinationen, Routen suchen...",
    "search.noResults": "Keine Ergebnisse gefunden",
    "search.quickLinks": "Schnelllinks",
    "search.hint": "Tippen zum Suchen",
    "search.toClose": "zum Schließen",

    // Favorites
    "favorites.title": "Meine Favoriten",
    "favorites.subtitle": "Ihre gespeicherten Yachten und Routen",
    "favorites.empty": "Noch keine Favoriten",
    "favorites.emptyDesc": "Speichern Sie Yachten und Routen, die Ihnen gefallen, indem Sie auf das Herzsymbol klicken",
    "favorites.browseYachts": "Yachten durchsuchen",
    "favorites.browseItineraries": "Routen durchsuchen",
    "favorites.yachts": "Yachten",
    "favorites.itineraries": "Routen",
    "favorites.destinations": "Destinationen",
    "favorites.clearAll": "Alle löschen",
    "favorites.addedToFavorites": "Zu Favoriten hinzugefügt",
    "favorites.removedFromFavorites": "Von Favoriten entfernt",
    "common.whatsapp": "WhatsApp",
    "common.loading": "Laden...",
    "common.from": "Ab",
    "common.perWeek": "pro Woche",
    "common.share": "Teilen",

    // Blog
    "blog.badge": "Unser Blog",
    "blog.title": "Blaue Reise Einblicke & Reisetipps",
    "blog.subtitle": "Expertenrat, Reiseführer und Insider-Tipps für Ihr perfektes Yacht-Charter-Erlebnis",
    "blog.allPosts": "Alle Beiträge",
    "blog.destinations": "Reiseziele",
    "blog.tips": "Tipps & Ratschläge",
    "blog.guides": "Reiseführer",
    "blog.news": "Neuigkeiten",
    "blog.readMore": "Weiterlesen",
    "blog.minRead": "Min. Lesezeit",
    "blog.backToBlog": "Zurück zum Blog",
    "blog.relatedArticles": "Verwandte Artikel",
    "blog.moreFromBlog": "Mehr aus unserem Blog",
    "blog.popularTopics": "Beliebte Themen",
    "blog.readyForCruise": "Bereit für Ihre Blaue Reise?",
    "blog.contactUsDesc": "Kontaktieren Sie uns, um Ihr perfektes Yachtcharter-Erlebnis entlang der türkischen Küste zu planen.",
    "blog.getQuote": "Angebot Anfordern",
    "blog.stayUpdated": "Bleiben Sie mit unseren neuesten Artikeln auf dem Laufenden",
    "blog.subscribeDesc": "Abonnieren Sie unseren Newsletter für exklusive Reisetipps, Sonderangebote und Insider-Guides zur türkischen Küste.",
    "blog.subscribeNow": "Jetzt Abonnieren",
    "blog.shareArticle": "Diesen Artikel teilen:",
    "blog.noPosts": "Keine Beiträge in dieser Kategorie gefunden.",

    // Destinations
    "destinations.badge": "Türkei Entdecken",
    "destinations.title": "Segelziele",
    "destinations.subtitle": "Entdecken Sie die atemberaubenden Häfen und Küstenjuwelen der türkischen Türkisküste, jedes mit einzigartigen Erlebnissen für Ihr Blaue-Reise-Abenteuer",
    "destinations.turquoiseAwaits": "Die Türkisküste Erwartet Sie",
    "destinations.turquoiseDesc": "Die Südwestküste der Türkei beherbergt einige der spektakulärsten Segelgewässer des Mittelmeers. Von antiken Hafenstädten bis zu unberührten Buchten bietet jedes Ziel seinen eigenen Charakter und Attraktionen.",
    "destinations.explore": "Erkunden",
    "destinations.notSure": "Nicht sicher, wo Sie anfangen sollen?",
    "destinations.notSureDesc": "Unser Team kennt jede Bucht und jeden Hafen entlang der türkischen Küste. Lassen Sie uns Ihnen helfen, die perfekte Route für Ihre Traum-Blaue-Reise zu wählen.",
    "destinations.contactExperts": "Kontaktieren Sie Unsere Experten",
    "destinations.about": "Über",
    "destinations.whyVisit": "Warum Besuchen",
    "destinations.mustSee": "Sehenswürdigkeiten",
    "destinations.itinerariesFrom": "Routen ab",
    "destinations.planCruise": "Planen Sie Ihre",
    "destinations.planCruiseDesc": "Kontaktieren Sie uns, um Ihre perfekte Blaue Reise zu planen ab",
    "destinations.idealFor": "Ideal Für",
    "destinations.bestTime": "Beste Reisezeit",
    "destinations.sailInStyle": "Segeln",
    "destinations.sailInStyleDesc": "Entdecken Sie unsere Flotte von Luxus-Gulets, alle verfügbar für Charter ab",
    "destinations.exploreOther": "Andere Ziele Erkunden",
    "destinations.viewAll": "Alle Ziele Ansehen",
    "destinations.allDestinations": "Alle Ziele",
    "destinations.turkey": "Türkei",

    // Newsletter
    "newsletter.title": "Abonnieren Sie Unseren Newsletter",
    "newsletter.subtitle": "Erhalten Sie exklusive Reisetipps, Sonderangebote und Insider-Guides zur türkischen Küste direkt in Ihren Posteingang.",
    "newsletter.placeholder": "Ihre E-Mail-Adresse eingeben",
    "newsletter.subscribe": "Jetzt Abonnieren",
    "newsletter.subscribing": "Wird abonniert...",
    "newsletter.success": "Vielen Dank für Ihre Anmeldung! Prüfen Sie Ihren Posteingang für eine Bestätigungs-E-Mail.",
    "newsletter.error": "Etwas ist schief gelaufen. Bitte versuchen Sie es später erneut.",
    "newsletter.invalidEmail": "Bitte geben Sie eine gültige E-Mail-Adresse ein",
    "newsletter.required": "Bitte geben Sie Ihre E-Mail-Adresse ein",
    "newsletter.privacy": "Kein Spam, jederzeit abmelden. Wir respektieren Ihre Privatsphäre.",
    "newsletter.compact.title": "Newsletter",
    "newsletter.compact.subtitle": "Reisetipps & exklusive Angebote erhalten",
    "newsletter.compact.subscribed": "Abonniert!",
  },
  fr: {
    // Navigation
    "nav.home": "Accueil",
    "nav.yachts": "Nos Yachts",
    "nav.itineraries": "Itinéraires",
    "nav.destinations": "Destinations",
    "nav.about": "À Propos",
    "nav.blog": "Blog",
    "nav.contact": "Contact",
    "nav.booking": "Réserver",

    // Home Hero
    "home.hero.badge": "Croisière Bleue de Luxe Depuis 1989",
    "home.hero.title": "Découvrez la Côte Turquoise de Turquie dans un Luxe Ultime",
    "home.hero.subtitle": "Vivez une croisière bleue inoubliable à bord de nos goélettes artisanales. Des eaux cristallines, des ruines antiques et un service cinq étoiles vous attendent.",
    "home.hero.cta.fleet": "Explorer Notre Flotte",
    "home.hero.cta.contact": "Demander un Devis",

    // Home Features
    "home.features.experience.title": "35+ Ans d'Expérience",
    "home.features.experience.desc": "La confiance de milliers de clients depuis 1989",
    "home.features.crew.title": "Équipage Professionnel",
    "home.features.crew.desc": "Capitaine expérimenté et personnel attentionné",
    "home.features.cuisine.title": "Cuisine Gastronomique",
    "home.features.cuisine.desc": "Pension complète avec délices méditerranéens",
    "home.features.certified.title": "Certifié TÜRSAB",
    "home.features.certified.desc": "Agence de voyage agréée #1739",

    // Home Fleet
    "home.fleet.badge": "Notre Flotte",
    "home.fleet.title": "Goélettes de Luxe Artisanales",
    "home.fleet.subtitle": "Choisissez parmi notre collection de goélettes soigneusement entretenues, chacune offrant un caractère unique et des équipements de classe mondiale.",
    "home.fleet.viewAll": "Voir Tous les Yachts",

    // Home Itineraries
    "home.itineraries.badge": "Itinéraires",
    "home.itineraries.title": "Explorez Nos Routes",
    "home.itineraries.subtitle": "Découvrez le meilleur de la Riviera turque avec nos routes de navigation soigneusement planifiées.",
    "home.itineraries.viewAll": "Voir Tous les Itinéraires",

    // Home About
    "home.about.title": "Votre Porte vers le Rêve Méditerranéen",
    "home.about.desc1": "Depuis 1989, Holiday Yacht crée des expériences de croisière bleue inoubliables le long de la magnifique Côte Turquoise de Turquie. En tant que membre de la famille Light Tours, nous combinons des décennies d'expertise maritime avec une authentique hospitalité turque.",
    "home.about.desc2": "Notre flotte de goélettes artisanales représente le meilleur de la construction navale traditionnelle turque, enrichie de conforts et équipements modernes.",

    // Home Stats
    "home.stats.years": "Années d'Excellence",
    "home.stats.yachts": "Goélettes de Luxe",
    "home.stats.guests": "Clients Satisfaits",
    "home.stats.support": "Support",
    "home.stats.satisfaction": "Satisfaction",
    "home.stats.destinations": "Destinations",

    // Home Testimonials
    "home.testimonials.badge": "Témoignages",
    "home.testimonials.title": "Ce Que Disent Nos Clients",
    "home.testimonial1": "Une expérience absolument magique ! L'équipage était exceptionnel, la nourriture incroyable et les paysages à couper le souffle. Nous reviendrons certainement !",
    "home.testimonial2": "De la réservation au débarquement, tout était parfait. Le yacht était magnifique et impeccablement entretenu. Les meilleures vacances que nous ayons jamais eues !",
    "home.testimonial3": "L'attention aux détails est remarquable. Nager dans des baies cristallines et dîner sous les étoiles - il n'y a pas mieux.",

    // Home CTA
    "home.cta.title": "Prêt pour Votre Voyage de Rêve ?",
    "home.cta.subtitle": "Laissez-nous vous aider à planifier l'expérience de croisière bleue parfaite. Contactez-nous aujourd'hui pour un devis personnalisé.",
    "home.cta.button": "Planifiez Votre Voyage",

    // Home Partners
    "home.partners.partOf": "Membre de",

    // Yachts Page
    "yachts.badge": "Collection Premium de Goélettes",
    "yachts.title": "Notre Flotte",
    "yachts.subtitle": "Découvrez notre sélection triée sur le volet de goélettes de luxe, chacune offrant un confort exceptionnel et un artisanat turc authentique.",
    "yachts.stats.gulets": "Goélettes de Luxe",
    "yachts.stats.capacity": "Capacité d'Accueil",
    "yachts.stats.length": "Gamme de Longueur",
    "yachts.stats.builtYears": "Années de Construction",
    "yachts.featured": "Yacht Vedette",
    "yachts.allYachts": "Tous les Yachts",
    "yachts.whyChoose": "Pourquoi Choisir Notre Flotte ?",
    "yachts.whyChooseDesc": "Chaque yacht de notre flotte répond aux normes les plus élevées de sécurité, confort et luxe.",
    "yachts.why.quality.title": "Qualité Premium",
    "yachts.why.quality.desc": "Chaque goélette est fabriquée à la main par des maîtres constructeurs utilisant des techniques traditionnelles et les meilleurs matériaux.",
    "yachts.why.crew.title": "Équipage Expert",
    "yachts.why.crew.desc": "Nos membres d'équipage professionnels sont formés pour fournir un service exceptionnel tout en assurant votre sécurité.",
    "yachts.why.amenities.title": "Équipements Modernes",
    "yachts.why.amenities.desc": "Profitez du confort contemporain incluant climatisation, WiFi et systèmes de divertissement.",

    // Yacht Filters
    "yachts.filters.title": "Filtrer les Yachts",
    "yachts.filters.guests": "Invités",
    "yachts.filters.length": "Longueur",
    "yachts.filters.weeklyPrice": "Prix Hebdomadaire",
    "yachts.filters.anyGuests": "Toute capacité",
    "yachts.filters.anyLength": "Toute longueur",
    "yachts.filters.anyPrice": "Tout prix",
    "yachts.filters.under15k": "Moins de 15 000€",
    "yachts.filters.under20k": "Moins de 20 000€",
    "yachts.filters.under25k": "Moins de 25 000€",
    "yachts.filters.clear": "Effacer les filtres",
    "yachts.filters.active": "Actif",
    "yachts.filters.noResults": "Aucun yacht ne correspond à vos filtres",
    "yachts.filters.noResultsDesc": "Essayez d'ajuster vos critères de filtre",

    // Yacht Details
    "yacht.cabins": "Cabines",
    "yacht.guests": "Invités",
    "yacht.length": "Longueur",
    "yacht.crew": "Équipage",
    "yacht.priceFrom": "À partir de",
    "yacht.perWeek": "/semaine",
    "yacht.bookNow": "Réserver Ce Yacht",
    "yacht.requestQuote": "Demander un Devis",
    "yacht.amenities": "Équipements",
    "yacht.specifications": "Spécifications",
    "yacht.gallery": "Galerie",
    "yacht.overview": "Aperçu",
    "yacht.features": "Caractéristiques",
    "yacht.seasonPrices": "Prix Saisonniers",
    "yacht.lowSeason": "Basse Saison",
    "yacht.midSeason": "Moyenne Saison",
    "yacht.highSeason": "Haute Saison",
    "yacht.aprilMay": "Avril - Mai",
    "yacht.juneSeptember": "Juin & Septembre",
    "yacht.julyAugust": "Juillet - Août",
    "yacht.october": "Octobre",
    "yacht.perDayShort": "/jour",

    // Booking
    "booking.title": "Réserver Votre Charter",
    "booking.subtitle": "Vérifiez la disponibilité et réservez le yacht de vos rêves en quelques étapes.",
    "booking.selectYacht": "Sélectionnez Votre Yacht",
    "booking.selectYachtDesc": "Choisissez parmi notre flotte de goélettes de luxe.",
    "booking.selectDates": "Sélectionnez Vos Dates",
    "booking.minNights": "Min. 7 nuits",
    "booking.available": "Disponible",
    "booking.booked": "Réservé",
    "booking.selected": "Sélectionné",
    "booking.checkIn": "Arrivée",
    "booking.checkOut": "Départ",
    "booking.duration": "Durée",
    "booking.nights": "nuits",
    "booking.guestDetails": "Détails des Invités",
    "booking.firstName": "Prénom",
    "booking.lastName": "Nom",
    "booking.email": "Adresse Email",
    "booking.phone": "Numéro de Téléphone",
    "booking.country": "Pays",
    "booking.guests": "Nombre d'Invités",
    "booking.specialRequests": "Demandes Spéciales",
    "booking.submit": "Demander une Réservation",
    "booking.changeYacht": "← Changer de Yacht",
    "booking.whyBookDirect": "Pourquoi Réserver Directement Chez Nous ?",
    "booking.bestPrice": "Garantie Meilleur Prix",
    "booking.noHiddenFees": "Pas de Frais Cachés",
    "booking.flexibleCancellation": "Annulation Flexible",
    "booking.support247": "Support 24/7",
    "booking.needHelp": "Besoin d'aide pour votre réservation ?",

    // Booking Form
    "bookingForm.confirmation": "Confirmation",
    "bookingForm.priceSummary": "Résumé du Prix",
    "bookingForm.fullBoardIncluded": "Pension complète incluse",
    "bookingForm.total": "Total",
    "bookingForm.continueToDetails": "Continuer vers les Détails",
    "bookingForm.guestInfo": "Informations sur l'Invité",
    "bookingForm.firstNameRequired": "Le prénom est requis",
    "bookingForm.lastNameRequired": "Le nom est requis",
    "bookingForm.emailRequired": "L'email est requis",
    "bookingForm.emailInvalid": "Adresse email invalide",
    "bookingForm.phoneRequired": "Le téléphone est requis",
    "bookingForm.countryRequired": "Le pays est requis",
    "bookingForm.guest": "invité",
    "bookingForm.specialRequestsPlaceholder": "Exigences alimentaires, occasions spéciales ou préférences...",
    "bookingForm.agreeToTerms": "J'accepte les",
    "bookingForm.termsConditions": "Conditions Générales",
    "bookingForm.and": "et la",
    "bookingForm.privacyPolicy": "Politique de Confidentialité",
    "bookingForm.termsRequired": "Vous devez accepter les conditions",
    "bookingForm.back": "Retour",
    "bookingForm.requestSubmitted": "Demande de Réservation Envoyée !",
    "bookingForm.thankYou": "Merci pour votre intérêt pour",
    "bookingForm.willContact": "Notre équipe examinera votre demande et vous contactera dans les 24 heures pour confirmer votre réservation.",
    "bookingForm.bookingSummary": "Résumé de la Réservation",
    "bookingForm.yacht": "Yacht",
    "bookingForm.dates": "Dates",
    "bookingForm.returnHome": "Retour à l'Accueil",

    // Calendar
    "calendar.selectDates": "Sélectionnez Vos Dates",
    "calendar.minNights": "Min. {min} nuits",
    "calendar.available": "Disponible",
    "calendar.booked": "Réservé",
    "calendar.selected": "Sélectionné",
    "calendar.checkIn": "Arrivée",
    "calendar.checkOut": "Départ",
    "calendar.duration": "Durée",
    "calendar.nights": "nuits",
    "calendar.minNightsWarning": "Veuillez sélectionner au moins {min} nuits",

    // Yacht Detail Page
    "yachtDetail.backToFleet": "Retour à la Flotte",
    "yachtDetail.about": "À Propos de",
    "yachtDetail.photoGallery": "Galerie Photo",
    "yachtDetail.amenitiesFeatures": "Équipements & Caractéristiques",
    "yachtDetail.startingFrom": "À partir de",
    "yachtDetail.perWeek": "par semaine",
    "yachtDetail.perDay": "par jour",
    "yachtDetail.minDays": "Minimum {days} jours de charter",
    "yachtDetail.notIncluded": "Non inclus :",
    "yachtDetail.callForQuote": "Appeler pour un Devis",
    "yachtDetail.sendInquiry": "Envoyer une Demande",
    "yachtDetail.charterIncludes": "Le charter comprend :",
    "yachtDetail.professionalCrew": "Équipage professionnel",
    "yachtDetail.fullBoardMeals": "Pension complète",
    "yachtDetail.fuelCruising": "Carburant pour la croisière",
    "yachtDetail.waterSports": "Équipement de sports nautiques",
    "yachtDetail.portFees": "Frais de port",
    "yachtDetail.built": "Construit",
    "yachtDetail.renovated": "Rénové",

    // Itinerary Detail Page
    "itineraryDetail.allItineraries": "Tous les Itinéraires",
    "itineraryDetail.days": "Jours",
    "itineraryDetail.dayByDay": "Itinéraire Jour par Jour",
    "itineraryDetail.dayByDayDesc": "Votre voyage se déroule avec des arrêts, activités et expériences soigneusement planifiés pour présenter le meilleur de la région.",
    "itineraryDetail.recommendedYachts": "Yachts Recommandés",
    "itineraryDetail.recommendedYachtsDesc": "Ces yachts sont parfaitement adaptés à cet itinéraire, offrant la combinaison idéale de confort et de capacité.",
    "itineraryDetail.readyToExperience": "Prêt à Vivre Cette Route ?",
    "itineraryDetail.contactUs": "Contactez-nous pour vérifier la disponibilité et recevoir un devis personnalisé pour votre aventure en voile de rêve.",
    "itineraryDetail.getQuote": "Obtenir un Devis",

    // Contact
    "contact.title": "Contactez-Nous",
    "contact.subtitle": "Des questions ou prêt à réserver le voyage de vos rêves ?",
    "contact.phone": "Téléphone",
    "contact.email": "Email",
    "contact.address": "Adresse",
    "contact.workingHours": "Heures d'Ouverture",
    "contact.sendMessage": "Envoyez-Nous un Message",
    "contact.sendMessageDesc": "Remplissez le formulaire et nous vous répondrons dans les 24 heures.",
    "contact.yourName": "Votre Nom",
    "contact.yourEmail": "Adresse Email",
    "contact.phoneNumber": "Numéro de Téléphone",
    "contact.subject": "Sujet",
    "contact.selectSubject": "Sélectionnez un sujet",
    "contact.subjectBooking": "Demande de Réservation",
    "contact.subjectQuote": "Demander un Devis",
    "contact.subjectInfo": "Informations Générales",
    "contact.subjectCustom": "Itinéraire Personnalisé",
    "contact.subjectOther": "Autre",
    "contact.interestedYacht": "Intéressé par un Yacht ?",
    "contact.selectYacht": "Sélectionnez un yacht (optionnel)",
    "contact.yourMessage": "Votre Message",
    "contact.messagePlaceholder": "Parlez-nous de votre voyage de rêve...",
    "contact.send": "Envoyer le Message",
    "contact.messageSent": "Message Envoyé !",
    "contact.messageSentDesc": "Merci de nous avoir contactés.",
    "contact.sendAnother": "Envoyer un Autre Message",
    "contact.immediateHelp": "Besoin d'Aide Immédiate ?",
    "contact.immediateHelpDesc": "Notre équipe est disponible pendant les heures de bureau.",

    // About
    "about.badge": "Depuis 1989",
    "about.title": "À Propos de Holiday Yacht",
    "about.subtitle": "Plus de trois décennies à créer des expériences de croisière bleue inoubliables.",
    "about.stats.years": "Années d'Expérience",
    "about.stats.gulets": "Goélettes de Luxe",
    "about.stats.guests": "Clients Satisfaits",
    "about.stats.destinations": "Destinations",
    "about.story.badge": "Notre Histoire",
    "about.story.title": "Un Héritage d'Excellence sur la Côte Turquoise",
    "about.story.p1": "Fondée en 1989 dans la charmante ville côtière de Fethiye, Holiday Yacht a commencé avec une vision simple : partager la beauté époustouflante de la côte méditerranéenne turque avec des voyageurs du monde entier.",
    "about.story.p2": "En tant que membre de la famille Light Tours, nous sommes passés d'une petite entreprise locale à l'une des sociétés de charter de yachts les plus respectées de la région.",
    "about.story.p3": "Aujourd'hui, nous continuons à respecter les valeurs qui nous guident depuis plus de 35 ans : un service exceptionnel, des expériences authentiques et un engagement inébranlable envers la satisfaction client.",
    "about.values.badge": "Nos Valeurs",
    "about.values.title": "Ce Qui Nous Distingue",
    "about.values.safety": "La Sécurité d'Abord",
    "about.values.safetyDesc": "Votre sécurité est notre priorité absolue.",
    "about.values.hospitality": "Hospitalité Authentique",
    "about.values.hospitalityDesc": "Découvrez l'authentique hospitalité turque.",
    "about.values.excellence": "Excellence",
    "about.values.excellenceDesc": "Nous visons l'excellence dans tous les aspects.",
    "about.values.personal": "Touche Personnelle",
    "about.values.personalDesc": "Chaque charter est adapté à vos préférences.",
    "about.team.badge": "Notre Équipe",
    "about.team.title": "Rencontrez l'Équipage",
    "about.team.subtitle": "Nos membres d'équipage expérimentés sont le cœur de Holiday Yacht.",
    "about.team.captain": "Capitaine",
    "about.team.captainDesc": "Navigateurs experts avec des décennies d'expérience.",
    "about.team.chef": "Chef",
    "about.team.chefDesc": "Artistes culinaires créant une délicieuse cuisine méditerranéenne.",
    "about.team.crew": "Équipage",
    "about.team.crewDesc": "Personnel attentionné assurant votre confort et sécurité.",
    "about.cta.title": "Prêt à Commencer Votre Voyage ?",
    "about.cta.subtitle": "Laissez-nous vous aider à créer des souvenirs qui dureront toute une vie.",
    "about.cta.fleet": "Explorer Notre Flotte",
    "about.cta.contact": "Contactez-Nous",
    "about.lightTours.title": "Membre de la Famille Light Tours",
    "about.lightTours.desc": "Holiday Yacht est fière de faire partie de Light Tours, une agence de voyage complète.",

    // Itineraries
    "itineraries.badge": "Routes Sélectionnées",
    "itineraries.title": "Itinéraires de Navigation",
    "itineraries.subtitle": "Découvrez la magie de la Riviera turque avec nos routes planifiées par des experts.",
    "itineraries.days": "Jours",
    "itineraries.highlights": "Points Forts",
    "itineraries.viewFull": "Voir l'Itinéraire Complet",
    "itineraries.dayByDay": "Itinéraire Jour par Jour",
    "itineraries.dayByDayDesc": "Votre voyage se déroule avec des arrêts et expériences soigneusement planifiés.",
    "itineraries.recommendedYachts": "Yachts Recommandés",
    "itineraries.recommendedYachtsDesc": "Ces yachts sont parfaitement adaptés à cet itinéraire.",
    "itineraries.customRoute": "Vous Cherchez une Route Personnalisée ?",
    "itineraries.customRouteDesc": "Nous pouvons créer un itinéraire personnalisé basé sur vos préférences.",
    "itineraries.requestCustom": "Demander un Itinéraire Personnalisé",
    "itineraries.readyToExperience": "Prêt à Vivre Cette Route ?",
    "itineraries.checkAvailability": "Vérifier la Disponibilité",
    "itineraries.getQuote": "Obtenir un Devis",
    "itineraries.allRoutes": "Tous les Itinéraires",

    // Error Pages
    "error.pageNotFound": "Page Non Trouvée",
    "error.pageNotFoundDesc": "La page que vous cherchez semble avoir pris la mer. Peut-être explore-t-elle la côte turque !",
    "error.backToHome": "Retour à l'Accueil",
    "error.viewFleet": "Voir Notre Flotte",
    "error.contactUs": "Contactez-Nous",

    // Footer
    "footer.description": "Charters de goélettes premium le long de la magnifique Côte Turquoise de Turquie depuis 1989.",
    "footer.quickLinks": "Liens Rapides",
    "footer.contactInfo": "Coordonnées",
    "footer.followUs": "Suivez-Nous",
    "footer.rights": "Tous droits réservés.",
    "footer.tursab": "Licence TÜRSAB #1739",
    "footer.workingHours": "Lun - Sam : 09h00 - 18h00",

    // Common
    "common.select": "Sélectionner",
    "common.viewDetails": "Voir les Détails",
    "common.learnMore": "En Savoir Plus",
    "common.callUs": "Appelez-Nous",

    // Search
    "search.placeholder": "Rechercher yachts, destinations, itinéraires...",
    "search.noResults": "Aucun résultat trouvé",
    "search.quickLinks": "Liens Rapides",
    "search.hint": "Tapez pour rechercher",
    "search.toClose": "pour fermer",

    // Favorites
    "favorites.title": "Mes Favoris",
    "favorites.subtitle": "Vos yachts et itinéraires sauvegardés",
    "favorites.empty": "Pas encore de favoris",
    "favorites.emptyDesc": "Sauvegardez les yachts et itinéraires que vous aimez en cliquant sur l'icône cœur",
    "favorites.browseYachts": "Parcourir les Yachts",
    "favorites.browseItineraries": "Parcourir les Itinéraires",
    "favorites.yachts": "Yachts",
    "favorites.itineraries": "Itinéraires",
    "favorites.destinations": "Destinations",
    "favorites.clearAll": "Tout Effacer",
    "favorites.addedToFavorites": "Ajouté aux favoris",
    "favorites.removedFromFavorites": "Retiré des favoris",

    "common.whatsapp": "WhatsApp",
    "common.loading": "Chargement...",
    "common.from": "À partir de",
    "common.perWeek": "par semaine",
    "common.share": "Partager",

    // Blog
    "blog.badge": "Notre Blog",
    "blog.title": "Aperçus de Croisière Bleue & Conseils de Voyage",
    "blog.subtitle": "Conseils d'experts, guides de destination et astuces d'initiés pour votre expérience parfaite de charter de yacht",
    "blog.allPosts": "Tous les Articles",
    "blog.destinations": "Destinations",
    "blog.tips": "Conseils & Astuces",
    "blog.guides": "Guides",
    "blog.news": "Actualités",
    "blog.readMore": "Lire la Suite",
    "blog.minRead": "min de lecture",
    "blog.backToBlog": "Retour au Blog",
    "blog.relatedArticles": "Articles Connexes",
    "blog.moreFromBlog": "Plus de Notre Blog",
    "blog.popularTopics": "Sujets Populaires",
    "blog.readyForCruise": "Prêt pour Votre Croisière Bleue ?",
    "blog.contactUsDesc": "Contactez-nous pour planifier votre expérience parfaite de charter de yacht le long de la côte turque.",
    "blog.getQuote": "Obtenir un Devis",
    "blog.stayUpdated": "Restez Informé avec Nos Derniers Articles",
    "blog.subscribeDesc": "Abonnez-vous à notre newsletter pour des conseils de voyage exclusifs, des offres spéciales et des guides d'initiés sur la côte turque.",
    "blog.subscribeNow": "S'abonner Maintenant",
    "blog.shareArticle": "Partagez cet article :",
    "blog.noPosts": "Aucun article trouvé dans cette catégorie.",

    // Destinations
    "destinations.badge": "Explorer la Turquie",
    "destinations.title": "Destinations de Navigation",
    "destinations.subtitle": "Découvrez les ports magnifiques et les joyaux côtiers de la Côte Turquoise de Turquie, chacun offrant des expériences uniques pour votre aventure de Croisière Bleue",
    "destinations.turquoiseAwaits": "La Côte Turquoise Vous Attend",
    "destinations.turquoiseDesc": "La côte sud-ouest de la Turquie abrite certaines des eaux de navigation les plus spectaculaires de la Méditerranée. Des anciennes villes portuaires aux baies immaculées, chaque destination offre son propre caractère et ses attractions.",
    "destinations.explore": "Explorer",
    "destinations.notSure": "Pas Sûr par Où Commencer ?",
    "destinations.notSureDesc": "Notre équipe connaît chaque baie et port le long de la côte turque. Laissez-nous vous aider à choisir l'itinéraire parfait pour votre Croisière Bleue de rêve.",
    "destinations.contactExperts": "Contacter Nos Experts",
    "destinations.about": "À Propos",
    "destinations.whyVisit": "Pourquoi Visiter",
    "destinations.mustSee": "Attractions Incontournables",
    "destinations.itinerariesFrom": "Itinéraires depuis",
    "destinations.planCruise": "Planifiez Votre",
    "destinations.planCruiseDesc": "Contactez-nous pour commencer à planifier votre parfaite Croisière Bleue depuis",
    "destinations.idealFor": "Idéal Pour",
    "destinations.bestTime": "Meilleure Période pour Visiter",
    "destinations.sailInStyle": "Naviguer",
    "destinations.sailInStyleDesc": "Explorez notre flotte de goélettes de luxe, toutes disponibles pour des charters depuis",
    "destinations.exploreOther": "Explorer d'Autres Destinations",
    "destinations.viewAll": "Voir Toutes les Destinations",
    "destinations.allDestinations": "Toutes les Destinations",
    "destinations.turkey": "Turquie",

    // Newsletter
    "newsletter.title": "Abonnez-vous à Notre Newsletter",
    "newsletter.subtitle": "Recevez des conseils de voyage exclusifs, des offres spéciales et des guides d'initiés sur la côte turque directement dans votre boîte de réception.",
    "newsletter.placeholder": "Entrez votre adresse email",
    "newsletter.subscribe": "S'abonner Maintenant",
    "newsletter.subscribing": "Inscription en cours...",
    "newsletter.success": "Merci de vous être abonné ! Vérifiez votre boîte de réception pour un email de confirmation.",
    "newsletter.error": "Une erreur s'est produite. Veuillez réessayer plus tard.",
    "newsletter.invalidEmail": "Veuillez entrer une adresse email valide",
    "newsletter.required": "Veuillez entrer votre adresse email",
    "newsletter.privacy": "Pas de spam, désabonnement à tout moment. Nous respectons votre vie privée.",
    "newsletter.compact.title": "Newsletter",
    "newsletter.compact.subtitle": "Recevez des conseils de voyage & offres exclusives",
    "newsletter.compact.subscribed": "Abonné !",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = localStorage.getItem("language") as Language;
    if (saved && ["en", "de", "fr"].includes(saved)) {
      setLanguageState(saved);
    } else {
      const browserLang = navigator.language.split("-")[0];
      if (browserLang === "de") setLanguageState("de");
      else if (browserLang === "fr") setLanguageState("fr");
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
