const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '..', 'src', 'contexts', 'LanguageContext.tsx');
let content = fs.readFileSync(filePath, 'utf8');

// French translations - comprehensive
const frenchTranslations = `  fr: {
    // Navigation
    "nav.home": "Accueil",
    "nav.yachts": "Nos Yachts",
    "nav.itineraries": "Itinéraires",
    "nav.destinations": "Destinations",
    "nav.about": "À Propos",
    "nav.blog": "Blog",
    "nav.contact": "Contact",
    "nav.booking": "Réserver",

    // Home Hero
    "home.hero.badge": "Croisière de Luxe Depuis 1989",
    "home.hero.title": "Découvrez la Côte Turquoise de Turquie dans un Luxe Ultime",
    "home.hero.subtitle": "Vivez une croisière inoubliable à bord de nos goélettes artisanales. Eaux cristallines, ruines antiques et service cinq étoiles vous attendent.",
    "home.hero.cta.fleet": "Découvrir Notre Flotte",
    "home.hero.cta.contact": "Demander un Devis",

    // Home Features
    "home.features.experience.title": "35+ Ans d'Expérience",
    "home.features.experience.desc": "La confiance de milliers de clients depuis 1989",
    "home.features.crew.title": "Équipage Professionnel",
    "home.features.crew.desc": "Capitaine expérimenté et personnel attentionné",
    "home.features.cuisine.title": "Cuisine Gastronomique",
    "home.features.cuisine.desc": "Pension complète avec délices méditerranéens",
    "home.features.certified.title": "Certifié TÜRSAB",
    "home.features.certified.desc": "Agence de voyage agréée #1739",

    // Home Fleet
    "home.fleet.badge": "Notre Flotte",
    "home.fleet.title": "Goélettes de Luxe Artisanales",
    "home.fleet.subtitle": "Choisissez parmi notre collection de goélettes soigneusement entretenues, chacune offrant un caractère unique et des équipements de classe mondiale.",
    "home.fleet.viewAll": "Voir Tous les Yachts",

    // Home Itineraries
    "home.itineraries.badge": "Itinéraires",
    "home.itineraries.title": "Explorez Nos Routes",
    "home.itineraries.subtitle": "Découvrez le meilleur de la Riviera turque avec nos routes de navigation soigneusement sélectionnées.",
    "home.itineraries.viewAll": "Voir Tous les Itinéraires",

    // Home About
    "home.about.title": "Votre Porte vers le Rêve Méditerranéen",
    "home.about.desc1": "Depuis 1989, Holiday Yacht crée des expériences de croisière bleue inoubliables le long de la magnifique côte turquoise de Turquie. En tant que membre de la famille Light Tours, nous combinons des décennies d'expertise maritime avec une authentique hospitalité turque.",
    "home.about.desc2": "Notre flotte de goélettes artisanales représente le meilleur de la construction navale turque traditionnelle, enrichie de conforts et commodités modernes.",

    // Home Stats
    "home.stats.years": "Années d'Excellence",
    "home.stats.yachts": "Goélettes de Luxe",
    "home.stats.guests": "Clients Satisfaits",
    "home.stats.support": "Support",
    "home.stats.satisfaction": "Satisfaction",
    "home.stats.destinations": "Destinations",

    // Home Testimonials
    "home.testimonials.badge": "Témoignages",
    "home.testimonials.title": "Ce Que Disent Nos Clients",
    "home.testimonial1": "Une expérience absolument magique ! L'équipage était exceptionnel, la nourriture incroyable, et les paysages à couper le souffle. Nous reviendrons sans aucun doute !",
    "home.testimonial2": "De la réservation au débarquement, tout était parfait. Le yacht était magnifique et impeccablement entretenu. Les meilleures vacances de notre vie !",
    "home.testimonial3": "L'attention aux détails est remarquable. Nager dans des baies cristallines et dîner sous les étoiles - c'est le summum du bonheur.",

    // Home CTA
    "home.cta.title": "Prêt pour Votre Voyage de Rêve ?",
    "home.cta.subtitle": "Laissez-nous vous aider à planifier l'expérience de croisière bleue parfaite. Contactez-nous aujourd'hui pour un devis personnalisé.",
    "home.cta.button": "Planifier Votre Voyage",

    // Home Partners
    "home.partners.partOf": "Membre de",

    // Yachts Page
    "yachts.badge": "Collection Premium de Goélettes",
    "yachts.title": "Notre Flotte",
    "yachts.subtitle": "Découvrez notre sélection de goélettes de luxe soigneusement choisies, chacune offrant un confort exceptionnel et un artisanat turc authentique.",
    "yachts.stats.gulets": "Goélettes de Luxe",
    "yachts.stats.capacity": "Capacité d'Accueil",
    "yachts.stats.length": "Gamme de Longueur",
    "yachts.stats.builtYears": "Années de Construction",
    "yachts.featured": "Yacht Vedette",
    "yachts.allYachts": "Tous les Yachts",
    "yachts.whyChoose": "Pourquoi Choisir Notre Flotte ?",
    "yachts.whyChooseDesc": "Chaque yacht de notre flotte répond aux normes les plus élevées de sécurité, confort et luxe.",
    "yachts.why.quality.title": "Qualité Premium",
    "yachts.why.quality.desc": "Chaque goélette est fabriquée à la main par des maîtres constructeurs navals selon des techniques traditionnelles et les meilleurs matériaux.",
    "yachts.why.crew.title": "Équipage Expert",
    "yachts.why.crew.desc": "Nos membres d'équipage professionnels sont formés pour fournir un service exceptionnel tout en assurant votre sécurité.",
    "yachts.why.amenities.title": "Équipements Modernes",
    "yachts.why.amenities.desc": "Profitez du confort contemporain incluant climatisation, WiFi et systèmes de divertissement.",

    // Yacht Filters
    "yachts.filters.title": "Filtrer les Yachts",
    "yachts.filters.guests": "Invités",
    "yachts.filters.length": "Longueur",
    "yachts.filters.weeklyPrice": "Prix Hebdomadaire",
    "yachts.filters.anyGuests": "Toute capacité",
    "yachts.filters.anyLength": "Toute longueur",
    "yachts.filters.anyPrice": "Tout prix",
    "yachts.filters.under15k": "Moins de 15 000 €",
    "yachts.filters.under20k": "Moins de 20 000 €",
    "yachts.filters.under25k": "Moins de 25 000 €",
    "yachts.filters.clear": "Effacer les filtres",
    "yachts.filters.active": "Actif",
    "yachts.filters.noResults": "Aucun yacht ne correspond à vos filtres",
    "yachts.filters.noResultsDesc": "Essayez d'ajuster vos critères de filtrage",

    // Yacht Details
    "yacht.cabins": "Cabines",
    "yacht.guests": "Invités",
    "yacht.length": "Longueur",
    "yacht.crew": "Équipage",
    "yacht.priceFrom": "À partir de",
    "yacht.perWeek": "/semaine",
    "yacht.bookNow": "Réserver ce Yacht",
    "yacht.requestQuote": "Demander un Devis",
    "yacht.amenities": "Équipements",
    "yacht.specifications": "Spécifications",
    "yacht.gallery": "Galerie",
    "yacht.overview": "Aperçu",
    "yacht.features": "Caractéristiques",
    "yacht.seasonPrices": "Prix Saisonniers",
    "yacht.lowSeason": "Basse Saison",
    "yacht.midSeason": "Moyenne Saison",
    "yacht.highSeason": "Haute Saison",
    "yacht.built": "Construit",

    // Booking
    "booking.title": "Réservez Votre Charter",
    "booking.subtitle": "Vérifiez la disponibilité et réservez votre yacht de rêve en quelques étapes.",
    "booking.selectYacht": "Sélectionnez Votre Yacht",
    "booking.selectYachtDesc": "Choisissez parmi notre flotte de goélettes de luxe.",
    "booking.selectDates": "Sélectionnez Vos Dates",
    "booking.minNights": "Min. 7 nuits",
    "booking.available": "Disponible",
    "booking.booked": "Réservé",
    "booking.selected": "Sélectionné",
    "booking.checkIn": "Arrivée",
    "booking.checkOut": "Départ",
    "booking.duration": "Durée",
    "booking.nights": "nuits",
    "booking.guestDetails": "Détails des Invités",
    "booking.firstName": "Prénom",
    "booking.lastName": "Nom",
    "booking.email": "Adresse E-mail",
    "booking.phone": "Numéro de Téléphone",
    "booking.country": "Pays",
    "booking.guests": "Nombre d'Invités",
    "booking.specialRequests": "Demandes Spéciales",
    "booking.submit": "Demander une Réservation",
    "booking.changeYacht": "← Changer de Yacht",
    "booking.whyBookDirect": "Pourquoi Réserver Directement Chez Nous ?",
    "booking.bestPrice": "Garantie du Meilleur Prix",
    "booking.noHiddenFees": "Pas de Frais Cachés",
    "booking.flexibleCancellation": "Annulation Flexible",
    "booking.support247": "Support 24h/24",
    "booking.needHelp": "Besoin d'aide pour votre réservation ?",

    // Booking Form
    "bookingForm.confirmation": "Confirmation",
    "bookingForm.priceSummary": "Récapitulatif des Prix",
    "bookingForm.fullBoardIncluded": "Pension complète incluse",
    "bookingForm.total": "Total",
    "bookingForm.continueToDetails": "Continuer vers les Détails",
    "bookingForm.guestInfo": "Informations sur l'Invité",
    "bookingForm.firstNameRequired": "Le prénom est requis",
    "bookingForm.lastNameRequired": "Le nom est requis",
    "bookingForm.emailRequired": "L'e-mail est requis",
    "bookingForm.emailInvalid": "Adresse e-mail invalide",
    "bookingForm.phoneRequired": "Le téléphone est requis",
    "bookingForm.countryRequired": "Le pays est requis",
    "bookingForm.guest": "invité",
    "bookingForm.specialRequestsPlaceholder": "Régimes alimentaires, occasions spéciales ou préférences...",
    "bookingForm.agreeToTerms": "J'accepte les",
    "bookingForm.termsConditions": "Conditions Générales",
    "bookingForm.and": "et la",
    "bookingForm.privacyPolicy": "Politique de Confidentialité",
    "bookingForm.termsRequired": "Vous devez accepter les conditions",
    "bookingForm.back": "Retour",
    "bookingForm.requestSubmitted": "Demande de Réservation Envoyée !",
    "bookingForm.thankYou": "Merci pour votre intérêt pour",
    "bookingForm.willContact": "Notre équipe examinera votre demande et vous contactera dans les 24 heures pour confirmer votre réservation.",
    "bookingForm.bookingSummary": "Récapitulatif de la Réservation",
    "bookingForm.yacht": "Yacht",
    "bookingForm.dates": "Dates",
    "bookingForm.returnHome": "Retour à l'Accueil",

    // Calendar
    "calendar.selectDates": "Sélectionnez Vos Dates",
    "calendar.minNights": "Min. {min} nuits",
    "calendar.available": "Disponible",
    "calendar.booked": "Réservé",
    "calendar.selected": "Sélectionné",
    "calendar.checkIn": "Arrivée",
    "calendar.checkOut": "Départ",
    "calendar.duration": "Durée",
    "calendar.nights": "nuits",
    "calendar.minNightsWarning": "Veuillez sélectionner au moins {min} nuits",

    // Yacht Detail Page
    "yachtDetail.backToFleet": "Retour à la Flotte",
    "yachtDetail.about": "À Propos",
    "yachtDetail.photoGallery": "Galerie Photo",
    "yachtDetail.amenitiesFeatures": "Équipements et Caractéristiques",
    "yachtDetail.startingFrom": "À partir de",
    "yachtDetail.perWeek": "par semaine",
    "yachtDetail.callForQuote": "Appelez pour un Devis",
    "yachtDetail.sendInquiry": "Envoyer une Demande",
    "yachtDetail.charterIncludes": "La location inclut :",
    "yachtDetail.professionalCrew": "Équipage professionnel",
    "yachtDetail.fullBoardMeals": "Repas en pension complète",
    "yachtDetail.fuelCruising": "Carburant pour la croisière",
    "yachtDetail.waterSports": "Équipement de sports nautiques",
    "yachtDetail.portFees": "Frais de port",
    "yachtDetail.built": "Construit",
    "yachtDetail.renovated": "Rénové",

    // Itinerary Detail Page
    "itineraryDetail.allItineraries": "Tous les Itinéraires",
    "itineraryDetail.days": "Jours",
    "itineraryDetail.dayByDay": "Itinéraire Jour par Jour",
    "itineraryDetail.dayByDayDesc": "Votre voyage se déroule avec des escales, activités et expériences soigneusement planifiées pour vous montrer le meilleur de la région.",
    "itineraryDetail.recommendedYachts": "Yachts Recommandés",
    "itineraryDetail.recommendedYachtsDesc": "Ces yachts sont parfaitement adaptés à cet itinéraire, offrant la combinaison idéale de confort et de performance.",
    "itineraryDetail.readyToExperience": "Prêt à Vivre cette Route ?",
    "itineraryDetail.contactUs": "Contactez-nous pour vérifier la disponibilité et recevoir un devis personnalisé pour votre aventure de voile de rêve.",
    "itineraryDetail.getQuote": "Obtenir un Devis",

    // Contact
    "contact.title": "Contactez-Nous",
    "contact.subtitle": "Vous avez des questions ou êtes prêt à réserver votre voyage de rêve ?",
    "contact.phone": "Téléphone",
    "contact.email": "E-mail",
    "contact.address": "Adresse",
    "contact.workingHours": "Heures d'Ouverture",
    "contact.sendMessage": "Envoyez-Nous un Message",
    "contact.sendMessageDesc": "Remplissez le formulaire et nous vous répondrons dans les 24 heures.",
    "contact.yourName": "Votre Nom",
    "contact.yourEmail": "Adresse E-mail",
    "contact.phoneNumber": "Numéro de Téléphone",
    "contact.subject": "Sujet",
    "contact.selectSubject": "Sélectionnez un sujet",
    "contact.subjectBooking": "Demande de Réservation",
    "contact.subjectQuote": "Demander un Devis",
    "contact.subjectInfo": "Informations Générales",
    "contact.subjectCustom": "Itinéraire Personnalisé",
    "contact.subjectOther": "Autre",
    "contact.interestedYacht": "Intéressé par un Yacht ?",
    "contact.selectYacht": "Sélectionnez un yacht (optionnel)",
    "contact.yourMessage": "Votre Message",
    "contact.messagePlaceholder": "Parlez-nous de votre voyage de rêve...",
    "contact.send": "Envoyer le Message",
    "contact.messageSent": "Message Envoyé !",
    "contact.messageSentDesc": "Merci de nous avoir contactés.",
    "contact.sendAnother": "Envoyer un Autre Message",
    "contact.immediateHelp": "Besoin d'Aide Immédiate ?",
    "contact.immediateHelpDesc": "Notre équipe est disponible pendant les heures de bureau.",

    // About
    "about.badge": "Depuis 1989",
    "about.title": "À Propos de Holiday Yacht",
    "about.subtitle": "Plus de trois décennies à créer des expériences de croisière bleue inoubliables.",
    "about.stats.years": "Années d'Expérience",
    "about.stats.gulets": "Goélettes de Luxe",
    "about.stats.guests": "Clients Satisfaits",
    "about.stats.destinations": "Destinations",
    "about.story.badge": "Notre Histoire",
    "about.story.title": "Un Héritage d'Excellence sur la Côte Turquoise",
    "about.story.p1": "Fondé en 1989 dans la charmante ville côtière de Fethiye, Holiday Yacht a commencé avec une vision simple : partager la beauté époustouflante de la côte méditerranéenne turque avec des voyageurs du monde entier.",
    "about.story.p2": "En tant que membre de la famille Light Tours, nous sommes passés d'une petite entreprise locale à l'une des sociétés de charter de yachts les plus respectées de la région.",
    "about.story.p3": "Aujourd'hui, nous continuons à défendre les valeurs qui nous guident depuis plus de 35 ans : un service exceptionnel, des expériences authentiques et un engagement inébranlable envers la satisfaction des clients.",
    "about.values.badge": "Nos Valeurs",
    "about.values.title": "Ce Qui Nous Distingue",
    "about.values.safety": "Sécurité d'Abord",
    "about.values.safetyDesc": "Votre sécurité est notre priorité absolue.",
    "about.values.hospitality": "Hospitalité Authentique",
    "about.values.hospitalityDesc": "Vivez l'authentique hospitalité turque.",
    "about.values.excellence": "Excellence",
    "about.values.excellenceDesc": "Nous visons l'excellence dans tous les aspects.",
    "about.values.personal": "Touche Personnelle",
    "about.values.personalDesc": "Chaque charter est adapté à vos préférences.",
    "about.team.badge": "Notre Équipe",
    "about.team.title": "Rencontrez l'Équipage",
    "about.team.subtitle": "Nos membres d'équipage expérimentés sont le cœur de Holiday Yacht.",
    "about.team.captain": "Capitaine",
    "about.team.captainDesc": "Navigateurs experts avec des décennies d'expérience.",
    "about.team.chef": "Chef",
    "about.team.chefDesc": "Artistes culinaires créant une délicieuse cuisine méditerranéenne.",
    "about.team.crew": "Équipage",
    "about.team.crewDesc": "Personnel attentif assurant votre confort et votre sécurité.",
    "about.cta.title": "Prêt à Commencer Votre Voyage ?",
    "about.cta.subtitle": "Laissez-nous vous aider à créer des souvenirs qui dureront toute une vie.",
    "about.cta.fleet": "Découvrir Notre Flotte",
    "about.cta.contact": "Contactez-Nous",
    "about.lightTours.title": "Membre de la Famille Light Tours",
    "about.lightTours.desc": "Holiday Yacht est fier de faire partie de Light Tours, une agence de voyage complète.",

    // Itineraries
    "itineraries.badge": "Routes Sélectionnées",
    "itineraries.title": "Itinéraires de Navigation",
    "itineraries.subtitle": "Découvrez la magie de la Riviera turque avec nos routes expertement planifiées.",
    "itineraries.days": "Jours",
    "itineraries.highlights": "Points Forts",
    "itineraries.viewFull": "Voir l'Itinéraire Complet",
    "itineraries.dayByDay": "Itinéraire Jour par Jour",
    "itineraries.dayByDayDesc": "Votre voyage se déroule avec des escales et expériences soigneusement planifiées.",
    "itineraries.recommendedYachts": "Yachts Recommandés",
    "itineraries.recommendedYachtsDesc": "Ces yachts sont parfaitement adaptés à cet itinéraire.",
    "itineraries.customRoute": "Vous Cherchez une Route Personnalisée ?",
    "itineraries.customRouteDesc": "Nous pouvons créer un itinéraire personnalisé selon vos préférences.",
    "itineraries.requestCustom": "Demander un Itinéraire Personnalisé",
    "itineraries.readyToExperience": "Prêt à Vivre cette Route ?",
    "itineraries.checkAvailability": "Vérifier la Disponibilité",
    "itineraries.getQuote": "Obtenir un Devis",
    "itineraries.allRoutes": "Tous les Itinéraires",

    // Error Pages
    "error.pageNotFound": "Page Non Trouvée",
    "error.pageNotFoundDesc": "La page que vous recherchez semble avoir pris la mer. Peut-être explore-t-elle la côte turque !",
    "error.backToHome": "Retour à l'Accueil",
    "error.viewFleet": "Voir Notre Flotte",
    "error.contactUs": "Contactez-Nous",

    // Footer
    "footer.description": "Charters de goélettes premium le long de la magnifique côte turquoise de Turquie depuis 1989.",
    "footer.quickLinks": "Liens Rapides",
    "footer.contactInfo": "Informations de Contact",
    "footer.followUs": "Suivez-Nous",
    "footer.rights": "Tous droits réservés.",
    "footer.tursab": "Licence TÜRSAB #1739",
    "footer.workingHours": "Lun - Sam: 09:00 - 18:00",

    // Common
    "common.select": "Sélectionner",
    "common.viewDetails": "Voir les Détails",
    "common.learnMore": "En Savoir Plus",
    "common.callUs": "Appelez-Nous",
    "common.whatsapp": "WhatsApp",
    "common.loading": "Chargement...",
    "common.from": "À partir de",
    "common.perWeek": "par semaine",
    "common.share": "Partager",

    // Search
    "search.placeholder": "Rechercher yachts, destinations, itinéraires...",
    "search.noResults": "Aucun résultat trouvé",
    "search.quickLinks": "Liens Rapides",
    "search.hint": "Tapez pour rechercher",
    "search.toClose": "pour fermer",

    // Favorites
    "favorites.title": "Mes Favoris",
    "favorites.subtitle": "Vos yachts et itinéraires sauvegardés",
    "favorites.empty": "Pas encore de favoris",
    "favorites.emptyDesc": "Sauvegardez les yachts et itinéraires que vous aimez en cliquant sur l'icône cœur",
    "favorites.browseYachts": "Parcourir les Yachts",
    "favorites.browseItineraries": "Parcourir les Itinéraires",
    "favorites.yachts": "Yachts",
    "favorites.itineraries": "Itinéraires",
    "favorites.destinations": "Destinations",
    "favorites.clearAll": "Tout Effacer",
    "favorites.addedToFavorites": "Ajouté aux favoris",
    "favorites.removedFromFavorites": "Retiré des favoris",

    // Blog
    "blog.badge": "Notre Blog",
    "blog.title": "Actualités Croisière Bleue et Conseils de Voyage",
    "blog.subtitle": "Conseils d'experts, guides de destination et astuces d'initiés pour votre expérience de charter parfaite",
    "blog.allPosts": "Tous les Articles",
    "blog.destinations": "Destinations",
    "blog.tips": "Conseils",
    "blog.guides": "Guides",
    "blog.news": "Actualités",
    "blog.readMore": "Lire la Suite",
    "blog.minRead": "min de lecture",
    "blog.backToBlog": "Retour au Blog",
    "blog.relatedArticles": "Articles Connexes",
    "blog.moreFromBlog": "Plus de Notre Blog",
    "blog.popularTopics": "Sujets Populaires",
    "blog.readyForCruise": "Prêt pour Votre Croisière Bleue ?",
    "blog.contactUsDesc": "Contactez-nous pour planifier votre expérience de charter parfaite le long de la côte turque.",
    "blog.getQuote": "Obtenir un Devis",
    "blog.stayUpdated": "Restez Informé de Nos Derniers Articles",
    "blog.subscribeDesc": "Abonnez-vous à notre newsletter pour des conseils de voyage exclusifs, des offres spéciales et des guides d'initiés sur la côte turque.",
    "blog.subscribeNow": "S'Abonner Maintenant",
    "blog.shareArticle": "Partager cet article :",
    "blog.noPosts": "Aucun article trouvé dans cette catégorie.",

    // Destinations
    "destinations.badge": "Explorer la Turquie",
    "destinations.title": "Destinations de Navigation",
    "destinations.subtitle": "Découvrez les ports et joyaux côtiers magnifiques de la côte turquoise de Turquie, chacun offrant des expériences uniques pour votre aventure Croisière Bleue",
    "destinations.turquoiseAwaits": "La Côte Turquoise Vous Attend",
    "destinations.turquoiseDesc": "La côte sud-ouest de la Turquie abrite certaines des eaux de navigation les plus spectaculaires de la Méditerranée. Des villes portuaires antiques aux baies préservées, chaque destination offre son propre caractère et ses attractions.",
    "destinations.explore": "Explorer",
    "destinations.notSure": "Vous Ne Savez Pas Par Où Commencer ?",
    "destinations.notSureDesc": "Notre équipe connaît chaque baie et port le long de la côte turque. Laissez-nous vous aider à choisir l'itinéraire parfait pour votre Croisière Bleue de rêve.",
    "destinations.contactExperts": "Contactez Nos Experts",
    "destinations.about": "À Propos",
    "destinations.whyVisit": "Pourquoi Visiter",
    "destinations.mustSee": "Attractions Incontournables",
    "destinations.itinerariesFrom": "Itinéraires depuis",
    "destinations.planCruise": "Planifiez Votre",
    "destinations.planCruiseDesc": "Contactez-nous pour commencer à planifier votre Croisière Bleue parfaite depuis",
    "destinations.idealFor": "Idéal Pour",
    "destinations.bestTime": "Meilleure Période pour Visiter",
    "destinations.sailInStyle": "Naviguez",
    "destinations.sailInStyleDesc": "Explorez notre flotte de goélettes de luxe, toutes disponibles pour des charters depuis",
    "destinations.exploreOther": "Explorer D'autres Destinations",
    "destinations.viewAll": "Voir Toutes les Destinations",
    "destinations.allDestinations": "Toutes les Destinations",
    "destinations.turkey": "Turquie",

    // Newsletter
    "newsletter.title": "Abonnez-vous à Notre Newsletter",
    "newsletter.subtitle": "Recevez des conseils de voyage exclusifs, des offres spéciales et des guides d'initiés sur la côte turque directement dans votre boîte mail.",
    "newsletter.placeholder": "Entrez votre adresse e-mail",
    "newsletter.subscribe": "S'Abonner Maintenant",
    "newsletter.subscribing": "Abonnement en cours...",
    "newsletter.success": "Merci de vous être abonné ! Consultez votre boîte mail pour un e-mail de confirmation.",
    "newsletter.error": "Une erreur s'est produite. Veuillez réessayer plus tard.",
    "newsletter.invalidEmail": "Veuillez entrer une adresse e-mail valide",
    "newsletter.required": "Veuillez entrer votre adresse e-mail",
    "newsletter.privacy": "Pas de spam, désabonnement à tout moment. Nous respectons votre vie privée.",
    "newsletter.compact.title": "Newsletter",
    "newsletter.compact.subtitle": "Recevez conseils voyage et offres exclusives",
    "newsletter.compact.subscribed": "Abonné !",
  },`;

// Find where to insert French (after German)
const deEndMatch = content.match(/de: \{[\s\S]*?\n  \},?\n\};/);
if (deEndMatch) {
  const insertPoint = content.lastIndexOf('};');
  const newContent = content.slice(0, insertPoint) + frenchTranslations + '\n};';
  fs.writeFileSync(filePath, newContent);
  console.log('Added French translations');
} else {
  console.error('Could not find insertion point');
}
